const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',world=WORLDS.find(w=>w.id==='sakura_zh-CN_01');
const nodes=[
['input',20,45,'偏好输入','语言 / 主题 / 氛围'],['prompt',190,45,'提示词组装','变量与模板'],['ch1',360,45,'第一章生成','共通剧情'],
['settings1',530,5,'场景设定提取','第一章'],['characters',530,105,'角色描述提取','三位角色'],['ch2',700,45,'第二章生成','包含三条路线'],['split',880,45,'路线拆分','A / B / C'],
['settings2',880,185,'场景设定提取','第二章'],['endings',880,285,'第三章生成','各路线结局'],['settings3',700,235,'结局场景提取','第三章'],['translation',530,235,'语言处理','目标语言'],['sprites',360,235,'角色资产生成','立绘 / 表情 / 头像'],['cg',190,235,'CG 生成','七个剧情场景'],['config',20,235,'世界配置','world.json'],['runtime',20,405,'运行与导出','Phaser / 独立版本']];
const edges=[['input','prompt'],['prompt','ch1'],['ch1','settings1'],['ch1','characters'],['settings1','ch2'],['characters','ch2'],['ch2','split'],['split','settings2'],['split','endings'],['settings2','settings3'],['endings','settings3'],['settings3','translation'],['translation','sprites'],['sprites','cg'],['cg','config'],['config','runtime']];
const steps=[
[['input'],'输入偏好','以校园、樱花与中文为示例输入。','preference_selection','input'],
[['prompt'],'组装提示词','将偏好填入提示词模板，检查必需变量与未替换占位符。','prompt_assembly / services/prompt-compiler.ts','prompt'],
[['ch1'],'生成共通章节','先生成第一章，建立角色关系与场景，为后续分支提供上下文。','chapter1_generation','script'],
[['settings1','characters'],'并行提取场景与角色','第一章生成后，同时提取场景设定与角色描述；两者完成后进入第二章。','chapter1_parallel → Promise.all','characters'],
[['ch2'],'生成第二章分支剧情','基于第一章和角色描述生成第二章内容，再将结果按路线拆分。','chapter2_branches','script'],
[['split'],'拆分三条路线','把第二章划分为凛、夏希、诗织三条路线，分别保留对应上下文。','split_routes','routes'],
[['settings2','endings'],'并行处理场景与结局','提取第二章场景设定，同时生成第三章结局。这是剧情流程中的第二处并行。','chapter2_parallel','routes'],
[['settings3'],'提取结局场景','在结局完成后提取第三章的场景信息，供后续 CG 生成使用。','extract_settings3','cg'],
[['translation'],'处理目标语言','剧情链路包含语言处理阶段。按目标语言整理剧情。','translation','script'],
[['sprites'],'生成角色资产','剧情流程结束后，处理角色立绘、表情和头像。','workflow-master: character_generation','characters'],
[['cg'],'生成剧情 CG','角色资产阶段完成后进入 CG 阶段，使用场景设定组织图像生成。此世界保留了七张 CG。','workflow-master: cg_generation','cg'],
[['config'],'写入世界配置','将章节路径、角色资产和 CG 映射写入 world.json，形成运行时可加载的内容包。','workflow-master: world_config','config'],
[['runtime'],'加载并运行游戏','原版运行时读取世界配置与脚本，呈现对白、角色和选项，并提供剧情树与独立导出。','standalone / src/core / src/screens','runtime']];
const chosenCG=ALL_WORLDS.filter(w=>['未闻花名的季节','春逝未满'].includes(w.title)).flatMap(w=>w.cgs);let t=0,playing=false,last=0,lastStep=-1,lastMode='',lastShot=-1;const nodeEls={},edgeEls=[];
function svg(tag,attrs){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e}
for(const[a,b]of edges){const x=nodes.find(n=>n[0]===a),y=nodes.find(n=>n[0]===b);let x1=x[1]+145,y1=x[2]+31,x2=y[1],y2=y[2]+31,d;if(y[1]<x[1]){x1=x[1];x2=y[1]+145}if(x[1]===y[1]){x1=x[1]+72;y1=x[2]+62;x2=y[1]+72;y2=y[2];d=`M${x1} ${y1} L${x2} ${y2}`}else{const mid=(x1+x2)/2;d=`M${x1} ${y1} C${mid} ${y1},${mid} ${y2},${x2} ${y2}`}if(a==='split'&&b==='endings')d='M1025 76 L1050 76 L1050 316 L1025 316';let e=svg('path',{d,class:'edge'});$('edges').append(e);edgeEls.push([a,b,e])}
for(const[id,x,y,title,sub]of nodes){let g=svg('g',{class:'node',transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':title+' '+sub});g.append(svg('rect',{width:145,height:62,rx:8}));let a=svg('text',{x:12,y:26}),b=svg('text',{x:12,y:45,class:'sub'});a.textContent=title;b.textContent=sub;g.append(a,b);g.onclick=()=>{playing=false;$('play').textContent='播放';t=5+steps.findIndex(s=>s[0].includes(id))*2;render()};g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();g.onclick()}};$('nodes').append(g);nodeEls[id]=g}
function artifact(type){$('artifact').replaceChildren();if(type==='characters'){world.characters.forEach(c=>{let im=new Image;im.src=c.src;im.alt=c.name;im.className='portrait';$('artifact').append(im)});return}if(type==='cg'||type==='runtime'){let im=new Image;im.src=type==='cg'?chosenCG[0].src:'screenshots/dialogue.png';im.alt=type==='cg'?'书页间的侧脸 CG':'游戏运行截图';$('artifact').append(im);return}let pre=document.createElement('pre');pre.textContent={input:'语言：简体中文\n主题：校园故事\n氛围：春日 / 樱花\n（示例输入）',prompt:'偏好参数 + 剧情模板\n→ 变量检查\n→ 提示词',script:world.chapters[lastStep>3?1:0].text.slice(0,160),routes:'共通章节\n  ├─ 凛路线 → 结局\n  ├─ 夏希路线 → 结局\n  └─ 诗织路线 → 结局',config:'world.json\n  chapters → 7 个章节\n  characters → 3 位角色\n  cgs → 7 张 CG'}[type]||'';$('artifact').append(pre)}
function render(){let mode=t<5?'intro':t<31?'dag':'ending';if(mode!==lastMode){for(const id of ['intro','dag','ending'])$(id).hidden=id!==mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));lastMode=mode;document.querySelectorAll('.timeline-labels span').forEach((label,i)=>{const active=i===['intro','dag','ending'].indexOf(mode);label.classList.toggle('active',active);if(active)label.setAttribute('aria-current','step');else label.removeAttribute('aria-current')})}if(mode==='intro')$('introShot').src=t<2.6?chosenCG[0].src:chosenCG[6].src;if(mode==='dag'){let s=Math.min(12,Math.floor((t-5)/2));if(s!==lastStep){lastStep=s;const step=steps[s],done=new Set(steps.slice(0,s).flatMap(x=>x[0]));for(const[id,e]of Object.entries(nodeEls))e.setAttribute('class','node'+(step[0].includes(id)?' active':done.has(id)?' done':''));edgeEls.forEach(([a,b,e])=>e.setAttribute('class','edge'+(step[0].includes(b)?' flow':done.has(b)?' done':'')));$('stepTitle').textContent=step[1];$('stepCount').textContent=`步骤 ${s+1} / 13`;$('detailTitle').textContent=step[1];$('detail').textContent=step[2];$('evidence').textContent=step[3];artifact(step[4])}}if(mode==='ending'){let k=Math.min(3,Math.floor((t-31)/4));if(k!==lastShot){lastShot=k;$('endShot').src='screenshots/'+['scene','dialogue','choice','tree'][k]+'.png';$('endTitle').textContent=['场景加载','角色对白','选项交互','剧情路线树'][k]}}$('seek').value=t;$('clock').textContent='00:'+String(Math.floor(t)).padStart(2,'0')+' / 00:47';document.querySelectorAll('.edge.flow').forEach(e=>e.style.animationPlayState=playing?'running':'paused')}
$('play').onclick=()=>{if(t>=47)t=0;playing=!playing;$('play').textContent=playing?'暂停':'播放';render()};$('restart').onclick=()=>{t=0;render()};$('seek').oninput=e=>{playing=false;$('play').textContent='播放';t=+e.target.value;render()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{t={intro:0,dag:5,ending:31}[b.dataset.mode];render()});function tick(now){if(playing){t=Math.min(47,t+Math.min(.2,(now-last)/1000));if(t===47){playing=false;$('play').textContent='重播'}render()}last=now;requestAnimationFrame(tick)}render();requestAnimationFrame(tick);
